name: artiqr
description: Generate Stunning QR Codes Using AI
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  process_run: ^0.12.3+2
  http: ^0.13.5
  flutter_spinkit: ^5.2.0
  path_provider: ^2.0.15
  url_launcher: ^6.1.7
  path_provider_windows: ^2.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.4
  bitsdojo_window: ^0.1.5
  animate_gradient: ^0.0.2+1
  window_manager: ^0.3.1
  audioplayers: ^4.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.4

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/